#
# Copyright 2025 OPPO.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Use the official Rocky Linux 9 image as a base
FROM rockylinux:9

RUN yum install -y java-1.8.0-openjdk-devel procps net-tools && yum clean all

ENV APP_HOME=/app
WORKDIR $APP_HOME

ADD dist $APP_HOME/curvine
RUN chmod +x $APP_HOME/curvine/bin/*


COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8995
EXPOSE 8996
EXPOSE 8997
EXPOSE 9000
EXPOSE 9001

ENTRYPOINT ["/entrypoint.sh"]

