# Use the official Rocky Linux 9 image as a base
FROM rockylinux:9

# 1. Install the basic toolchain and dependencies
RUN dnf install -y \
    fuse3 \
    fuse3-devel \
    clang \
    llvm \
    llvm-devel \
    git \
    wget \
    zip \
    unzip \
    nodejs \
    npm \
    java-1.8.0-openjdk-devel \
    && dnf clean all

# 2. Install the Rust toolchain
ENV RUSTUP_UPDATE_ROOT=https://mirrors.aliyun.com/rustup/rustup
ENV RUSTUP_DIST_SERVER=https://mirrors.aliyun.com/rustup
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable && \
    source $HOME/.cargo/env

# 3. Install protoc
RUN mkdir -p /app/protoc && cd /app/protoc && \
    curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v27.2/protoc-27.2-linux-x86_64.zip && \
    unzip protoc-27.2-linux-x86_64.zip && \
    chmod +x bin/protoc && \
    rm -f *.zip

# 4. Install Maven
RUN cd /app && \
    curl -LO https://downloads.apache.org/maven/maven-3/3.9.10/binaries/apache-maven-3.9.10-bin.tar.gz && \
    tar -xzf apache-maven-3.9.10-bin.tar.gz && \
    mv apache-maven-3.9.10 maven && \
    rm -f *.tar.gz

#5. Replace the configuration
RUN mkdir -p /app/maven/conf
COPY settings.xml /app/maven/conf/settings.xml

RUN mkdir -p /root/.cargo
COPY config /root/.cargo/config.toml

RUN echo "export PATH=\"\$PATH:/app/protoc/bin:/app/maven/bin\"" >> /root/.bashrc

# Add after all installation commands
RUN rm -rf \
    /var/cache/yum/* \
    /tmp/* \
    /var/tmp/*


WORKDIR /workspace
CMD source /root/.bashrc && bash
